name: 'Test'
on:
  issue_comment:
    types: [created]
  pull_request:
      types: [opened, reopened, closed]
jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Configure .env file
        run: |
          python -c "import base64; print(base64.b64encode(os.environ['MY_SECRET'].encode('ascii')))"
        shell: bash
        env:
          MY_SECRET : ${{secrets.MY_SECRET}}


 